version: "3.7"
services:
  dev:
    container_name: atlassian-developer-stack-vscode-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
        - USER_UID=1001
    hostname: asd
    command: code-server --auth none /home/${USER}/workspace/
    environment: 
      - GIT_CLONE_URL=git@bitbucket.org:phall_atlassian/atlassian-developer-stack.git
    volumes:
      - ~/.ssh:/home/${USER}/.ssh
      - ~/.gitconfig:/home/${USER}/.gitconfig
      - vscode-server:/home/${USER}/.local/share/code-server
      - workspace:/home/${USER}/workspace
    ports:
      - "8080:8080"
volumes:
  workspace:
  vscode-server: