version: "3.7"
services:
  dev:
    container_name: jira-frontend-vscode-remote
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
        - USER_UID=1001
    command: /bin/sh -c "while sleep 1000; do :; done"
    hostname: asd
    environment: 
      - GIT_CLONE_URL=ssh://git@stash.atlassian.com:7997/jiracloud/jira-frontend.git
      - NODE_OPTIONS=--max_old_space_size=4096
    ports:
      - "3000:3000"
      - "3443:3443"
      - "4040:4040"
    volumes:
      - ~/.ssh:/home/${USER}/.ssh
      - ~/.gitconfig:/home/${USER}/.gitconfig
      - ~/.npmrc:/home/${USER}/.npmrc
      - ~/.ngrok2:/home/${USER}/.ngrok2
      - workspace:/home/${USER}/workspace
volumes:
    workspace: